version: "3"

services:
  rs:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./durin/migrations:/pyenv/lib/python3.10/site-packages/durin/migrations
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py create_nro &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=netmesh
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - DEBUG=1
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - GMAPS_TOKEN=${GMAPS_TOKEN}
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=netmesh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

        #   mailserver:
        #     image: docker.io/mailserver/docker-mailserver:latest
        #     container_name: mailserver
        #     # If the FQDN for your mail-server is only two labels (eg: example.com),
        #     # you can assign this entirely to `hostname` and remove `domainname`.
        #     hostname: netmesh
        #     domainname: netmesh.pregi.net
        #     env_file: mailserver.env
        #     # More information about the mail-server ports:
        #     # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
        #     # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
        #     ports:
        #       - "25:25"    # SMTP  (explicit TLS => STARTTLS)
        #       - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
        #       - "465:465"  # ESMTP (implicit TLS)
        #       - "587:587"  # ESMTP (explicit TLS => STARTTLS)
        #       - "993:993"  # IMAP4 (implicit TLS)
        #     volumes:
        #       - ./docker-data/dms/mail-data/:/var/mail/
        #       - ./docker-data/dms/mail-state/:/var/mail-state/
        #       - ./docker-data/dms/mail-logs/:/var/log/mail/
        #       - ./docker-data/dms/config/:/tmp/docker-mailserver/
        #       - /etc/localtime:/etc/localtime:ro
        #     restart: always
        #     stop_grace_period: 1m
        #     cap_add:
        #       - NET_ADMIN
        #     healthcheck:
        #       test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
        #       timeout: 3s
        #       retries: 0
