name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build the stack
      run: docker-compose up -d
    - name: Start DB
      run: docker-compose run --rm rs sh -c "python manage.py wait_for_db"
    - name: Migrate
      run: docker-compose run --rm rs sh -c "python manage.py migrate"
    - name: Test
      run: docker-compose run --rm rs sh -c "python manage.py test"
    - name: Lint
      run: docker-compose run --rm rs sh -c "flake8"
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
      # mail server settings
      server_address: smtp.gmail.com
      server_port: 465
      # user credentials
      username: ${{ secrets.EMAIL_USERNAME }}
      password: ${{ secrets.EMAIL_PASSWORD }}
      # email subject
      subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      # email body as text
      body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      # comma-separated string, send email to
      to: maryjane.alpad@asti.dost.gov.ph
      # from email name
      from: ROBOT
