version: "3.9"

services:
  netmeshapp:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    command:
      - sh -c "python manage.py create_nro"
    environment:
      - DB_HOST=netmeshdb
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=1
      - GMAPS_TOKEN=${GMAPS_TOKEN}
    depends_on:
      - netmeshdb

  netmeshdb:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - netmeshapp
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
